### ISSUE TITLE
Concrete example?

### ISSUE THREAD

**Issue by svdasein** [hufftheweevil/node-red-contrib-things#1]
I think you've done a really great job of documenting the framework, but it'd be really nice to have a concrete example to refer to as well.  Do you think you could add one or two for reference?

**Comment by hufftheweevil** [comment]
Absolutely! I knew some examples would be required to fully understand it. I'll be working on them this week.

**Comment by hufftheweevil** [comment]
I added a couple of examples in https://github.com/hufftheweevil/node-red-contrib-things/commit/79099c6fb1b66d3222360e57204d65d60cfe3ce0

I'm sure I can come up with more complex ones, as it's hard to see the power in these nodes with simple examples. I'll make more when I find some time. If anyone has any suggestions, please let me know.

**Comment by xX-Nexus-Xx** [comment]
I just started playing around with these THINGS and do like the idea very much but struggeling to get your examples working as I do not have LIFX.

Would you be able to do a generic example by just defining a few lights (maybe 1 or 2 groups) and than control them (on,off, brightness) with the default UI elements as trigger. This would keep the example independant.

I do a lot with MQTT .. would it be possible to digest a JSON payload directly from an MQTT message?

thanks for this node .. I think this has great potential

**Comment by hufftheweevil** [comment]
Sure, I'll see what I can come up with.

I use MQTT as well for some things. It all depends how your MQTT messages are formatted. If the messages have a topic with one of your thing names, then you might need to simply `JSON parse` the payload. But that also assumes your payload is formatted properly for how you want to use it with the thing state.

**Comment by xX-Nexus-Xx** [comment]
Yes, the JSON parse i'm curently trying with manual and MQTT JSON payload, but when using the GET node with STATE property I'm getting a message payload object with lots of elements. one element for every character of the JSON string

`[{"id":"89c20d26.8ac7a","type":"Thing Get","z":"8be0c631.6a5418","nodeName":"","name":"Living Room 2","props":[{"msgProp":"payload","thingProp":"state","path":""}],"x":650,"y":1140,"wires":[["22bf6762.e136d8"]]},{"id":"22bf6762.e136d8","type":"debug","z":"8be0c631.6a5418","name":"group","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":870,"y":1140,"wires":[]},{"id":"d8d9df04.3ba52","type":"inject","z":"8be0c631.6a5418","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":390,"y":1140,"wires":[["89c20d26.8ac7a"]]},{"id":"7ca5354.19342cc","type":"json","z":"8be0c631.6a5418","name":"","property":"payload","action":"obj","pretty":false,"x":510,"y":1200,"wires":[["55947443.64fb2c"]]},{"id":"73035aba.aeebc4","type":"inject","z":"8be0c631.6a5418","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"battery\":60,\"elapsed\":16807,\"last_seen\":\"2020-10-14T13:46:06+11:00\",\"linkquality\":69,\"occupancy\":true,\"update_available\":false}","payloadType":"json","x":390,"y":1200,"wires":[["7ca5354.19342cc"]]},{"id":"55947443.64fb2c","type":"Thing Command","z":"8be0c631.6a5418","nodeName":"","name":"Living Room 2","command":"","commandType":"str","debug":false,"x":700,"y":1200,"wires":[]}]`

**Comment by hufftheweevil** [comment]
Ah, yes, I have experienced that once before. That means you are sending in a string as the payload to the *update* node, which it then treats as an enumerable object (`"hello"` becomes `{0:'h',1:'e',2:'l',3:'l',4:'o'}`. You should always send an object as the payload into the *update* node.

And based on the example there, the node after the JSON parse node is a *command* node. I think you are meaning to use the *update* node. Or perhaps I'm misunderstanding your example?

**Comment by xX-Nexus-Xx** [comment]
yes, I found that out the hard way ;) .. as all the state information are persistent

In your above example I always will have 5 elements in the object (even after restart).. is there way to either delete all the elements or provide an inital set of elements (e.g.  above object init state {0:'h',1:'e') so the rest of the elements are truncated?

**Comment by hufftheweevil** [comment]
Three ways:

1. Send in an object like `{0:undefined, 1:undefined, ...}`
2. Add `replace: true` to the message. This will cause the payload to completely replace the old state.
3. In the context sidebar tab, load the globals, then push the delete buttons next to `things`. But **caution**, this will wipe out all things until you re-deploy.

In the future, I'll see if I can add a little delete button for each state key in the Things Directory sidebar tab.

**Comment by xX-Nexus-Xx** [comment]
thanks a lot ... the replace:true did the trick!!

Somehow, the sidebar-tab does not show anything for me
![image](https://user-images.githubusercontent.com/2195190/95943474-aaffa880-0e31-11eb-81ec-1f9c357a3ecb.png)

**Comment by hufftheweevil** [comment]
I'll close this for now. If anyone has any other specific example requests, let me know. Or create your own to share!
