### ISSUE TITLE
Feature request:  STATUS information optional

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#10]
As you can see in the picture below, the status information in the THING nodes can become very lengthy and will overlap very quickly with other information.
![image](https://user-images.githubusercontent.com/2195190/97401280-9f89a280-1944-11eb-8c8e-20bc312a1361.png)

Is it possible to make this optional? (enable/disable)   or conditional? (only when ERR state)

thanks for considering

**Comment by hufftheweevil** [comment]
Indeed, I'm facing the same issue. I will make a change in the next release. Thanks!

**Comment by xX-Nexus-Xx** [comment]
im looking forward to it

**Comment by hufftheweevil** [comment]
Added in v3.0.0 which has been released as RC1 for now. It is not yet published on npm or Node-RED library. Install directly for now. Regular release will come early next week.
