### ISSUE TITLE
Feature request: Enhance filter for THING-LIST

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#11]
Hi , is it possible to enhance the filter options for THING-LIST ... ideally the same options you have in THING-Trigger. I especially would need the "is in Group" option

Additionally it would be great if the THING-List can optionally output a dedicate THING-state (like Trigger)

Trigger:
![image](https://user-images.githubusercontent.com/2195190/97535693-1fc90a00-1a10-11eb-9510-5ef67ef1e05c.png)

List:
![image](https://user-images.githubusercontent.com/2195190/97535724-2f485300-1a10-11eb-8384-704fd19aaac6.png)

thanks for considering

**Comment by hufftheweevil** [comment]
Added in v3.0.0 which has been released as RC1 for now. It is not yet published on npm or Node-RED library. Install directly for now. Regular release will come early next week.

**Comment by xX-Nexus-Xx** [comment]
Did you release v3.0.0 already? its not in the library yet

**Comment by hufftheweevil** [comment]
Not yet. It is available if you download directly from this repo as `v3.0.0-alpha`. I'm going to release a `beta` sometime this week. And then final release sometime next week.
