### ISSUE TITLE
Feature request:    "Ignore initialization" as permanent option in TRIGGER

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#12]
I'm sorry to come with that many requests but I really do like your THING node and rolling it out in all modules I have.

I have now realized that my TRIGGER's are getting raised when restarting which is not planned ;) .. example .. all my lights go on ;)

Is it possible to have the option of "Ignore initialization" as a permanent option not just in the selection as shown below?
![image](https://user-images.githubusercontent.com/2195190/97816387-fd254280-1ce8-11eb-9451-c718a8f9b639.png)

**Comment by hufftheweevil** [comment]
No worries about the feature requests, I'm always open to ideas.

I'm not sure what you mean by "permanent". Do you mean make it checked by default?

**Comment by xX-Nexus-Xx** [comment]
Sorry, not by default ... but available independent of any selection in the OUTPUT section. At this time it is not available when I select "On all state changes" nor "When any part.."

Is it possible to have it as a general option for the TRIGGER?

**Comment by hufftheweevil** [comment]
Ah, got it. Yes, I can implement that.

Might be a few days before full v3 release. I'm considering getting rid of the whole "Group" type concept and instead allowing *any* thing to have child *things* and group-like abilities.

**Comment by xX-Nexus-Xx** [comment]
Yes, I liked the GROUP idea initially but it is not really helpful. Your Parent-Child concept is much better.

There was a Parent-Child discussion in another issue-topic. Where you discussed the on how to handle different attributes in the CHILDs .I would recommend that whenever a PARENT attribute is updated it will overwrite the attribute in all CHILDs... but not the other way around.  Like in a family ;)

**Comment by hufftheweevil** [comment]
It supposed to work automatically. It's a great visual display of all your _things_, include their _state_ and _props_. It's a shame it's not working for you. Currently it works by establishing a websocket connection over port `8120` back to your Node-RED server. Is Node-RED running through a container of sorts that blocks that port?

**Comment by xX-Nexus-Xx** [comment]
Yes, I'm running my Test-NR in a container .. I will check to open the port

**Comment by hufftheweevil** [comment]
Yeah. v3 fixed that issue with the default status function producing a very long string.
