### ISSUE TITLE
Information:   TRIGGER-Thing does not recognize update (space at end of THING name)

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#13]
I was getting crazy because some of my TRIGGER-Thing nodes did not respond to an update!

The root-cause was (my mistake!) that I did a Copy-Paste with the Thing-Name which did added a empty space (" ") after the name==> "Switch.Kitchen " instead of "Switch.Kitchen"

![image](https://user-images.githubusercontent.com/2195190/97821307-0e307c80-1d06-11eb-816b-3e80ae41fcac.png)

Maybe you can truncate tailing spaces in THING-Names .. I will for sure check in future

**Comment by hufftheweevil** [comment]
Yeah, I think we could do that

**Comment by xX-Nexus-Xx** [comment]
yeah .. I can't see any design reason for that either ;)  .. unfortunately it adds a SPACE a the end when Copy-Paste
