### ISSUE TITLE
Feature Request:  Can you enable persistent storage for THINGs ?

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#15]
Hi, I'm now using your THINGs for all my entities in the house and it works great.

I have realized that the THINGS content is not persistent and that all content is lost after a restart of Node-Red or a redeploy of a module where a THING is configured.

Is it possible to enable the persistent storage capability for THINGs?

**Comment by hufftheweevil** [comment]
I believe that is beyond the scope of this package. Check out context in the Node-RED guide to see how you can set this up on your own: https://nodered.org/docs/user-guide/context#context-stores

**Comment by xX-Nexus-Xx** [comment]
I already have setup the persistant storage in Node-Red and it works for my normal Variables, but it looks like that you are overwriting or resetting the values on startup  when the THINGs are getting created.

As said, all my normal variables maintain their last state after a reboot of Node-Red ..but not the THINGs

**Comment by hufftheweevil** [comment]
Interesting - I thought this would have been handled automatically, based on how I set the things up. I will do some testing to see if I can figure out why not. Meanwhile, [v3.0.0-beta-2](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v3.0.0-beta-2) is available. I'm currently testing it in my live environment.

**Comment by xX-Nexus-Xx** [comment]
Yeah, let me know the outcome of your testing .. as said for me all THINGs content is re-initialized after Node-Red reboot ... would be good to understand if it is the same with you.

I had no time yet to test your beta .. but will do shortly.  Summer is coming here in Australia and my Sprinkler system is not automated yet ;)

**Comment by hufftheweevil** [comment]
I did some research and found why it's not working as we might expect it to. The reason is because once the global `things` object is only ever set once. Is is then referenced from there on out and modified. So the context API doesn't think anything was changed, and hence does not save anything to the file system.

A simple, but kind of hacky workaround to solve this would be to add an inject node with an internal of 30 seconds, linked to a change node that sets `global.something` to the current timestamp.

Full code:
```
[{"id":"3b79fa73.5ee896","type":"inject","z":"3bd4a308.2d8d1c","name":"","props":[],"repeat":"30","crontab":"","once":true,"onceDelay":0.1,"topic":"","x":890,"y":60,"wires":[["d4b3d0b3.376b"]]},{"id":"d4b3d0b3.376b","type":"change","z":"3bd4a308.2d8d1c","name":"","rules":[{"t":"set","p":"test","pt":"global","to":"","tot":"date"}],"action":"","property":"","from":"","to":"","reg":false,"x":1040,"y":60,"wires":[[]]}]
```

That will force the global context to always write to the file system.

**Comment by hufftheweevil** [comment]
@xX-Nexus-Xx Did that help?

**Comment by xX-Nexus-Xx** [comment]
Yes, that did help ;) ... I'm now updating a global variable whenever there is an event to my central THING-update.

Your trigger-node does have the option "Ignore initialization" and I did not checkmark it
![image](https://user-images.githubusercontent.com/2195190/100703237-37bcf080-33f7-11eb-9c8b-90ced87df6ce.png)


unfortunately there is no trigger-event after an restart and therefore my UI elements are not getting updated (see below) but I easily can modify this with an inject node.

![image](https://user-images.githubusercontent.com/2195190/100703020-d6951d00-33f6-11eb-8443-cbc7fb64a13f.png)
