### ISSUE TITLE
Setup missing

### ISSUE THREAD

**Issue by flic** [hufftheweevil/node-red-contrib-things#16]
I tried installing Things on v1.2.5 (latest-12), but Setup is missing. All other nodes are registered and shows up in the sidebar, but not Setup. No errors in the log.

I tried it on two different Node-Red installs, same result.

Any idea why?

Thanks.

**Comment by hufftheweevil** [comment]
@latest is currently v2.4.5 - not sure why it gave you that version.

And my apologizes to all for not getting v3-beta out yet. Work has been busier than expected. Hopefully I can get it published during this holiday weekend.
