### ISSUE TITLE
Examples, nodes missing

### ISSUE THREAD

**Issue by NietGiftig** [hufftheweevil/node-red-contrib-things#17]
After the last update ?
Not all nodes are installed
the examples are not complete.
There are nodes missing when you import the examples

after installing things
`
30 Nov 09:03:56 - [info] Installing module: node-red-contrib-things, version: 3.0.0
30 Nov 09:03:59 - [info] Installed module: node-red-contrib-things
30 Nov 09:03:59 - [info] Added node types:
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing Setup
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing Update
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing Trigger
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing Get
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing Test
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing List
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing Command
30 Nov 09:03:59 - [info]  - node-red-contrib-things:Thing Process
30 Nov 09:31:47 - [info] Stopping flows
30 Nov 09:31:48 - [info] Stopped flows
30 Nov 09:31:48 - [info] Waiting for missing types to be registered:
30 Nov 09:31:48 - [info]  - lifx server
30 Nov 09:31:48 - [info]  - lifx in
30 Nov 09:31:48 - [info]  - lifx out
30 Nov 09:32:01 - [info] Stopping flows
30 Nov 09:32:01 - [info] Stopped flows
30 Nov 09:32:01 - [info] Waiting for missing types to be registered:
30 Nov 09:32:01 - [info]  - lifx server
30 Nov 09:32:33 - [info] Stopping flows
30 Nov 09:32:33 - [info] Stopped flows
30 Nov 09:32:33 - [info] Starting flows
30 Nov 09:32:33 - [info] Started flows
`

**Comment by hufftheweevil** [comment]
Those missing nodes are from other libraries. However, the examples do need to be updated to match some of the recent changes. And I will try to make more generic examples to avoid missing nodes from other libraries.

Coming soon!

**Comment by xX-Nexus-Xx** [comment]
Great Nodes you have, I use them now in all of my flows.

However, I just use the basic functionality and have not used CHILDREN, PROPS, Custom functions or Commands.

I hope you can provide some examples on how these things work, as I'm keen to use them

thx for all your efforts

**Comment by hufftheweevil** [comment]
Added a few more in [v3.2.4](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v3.2.4)
