### ISSUE TITLE
Setup, and other nodes, still missing in action

### ISSUE THREAD

**Issue by flic** [hufftheweevil/node-red-contrib-things#18]
As I mentioned in #16, I have a problem with nodes missing. I thought I might as well wait for v3.0.0 and try the new version, but the problem seems to remain. I'm actually missing more nodes now.

I wanted to try it in a fresh environment, so I created a new container for the installation:

`docker run -p 1880:1880 nodered/node-red:latest-12
`

I installed Things from 'Manage palette', no errors:

30 Nov 11:00:07 - [info] Installing module: node-red-contrib-things, version: 3.0.0
30 Nov 11:00:09 - [info] Installed module: node-red-contrib-things
30 Nov 11:00:09 - [info] Added node types:
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing Setup
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing Update
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing Trigger
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing Get
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing Test
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing List
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing Command
30 Nov 11:00:09 - [info]  - node-red-contrib-things:Thing Process

...but this is the result:
![Skärmavbild 2020-11-30 kl  12 23 41](https://user-images.githubusercontent.com/400673/100604471-e5040b80-3306-11eb-9ce9-cf3157eb5170.png)

**Comment by hufftheweevil** [comment]
Fixed with v3.0.1

**Comment by fredrik-furtenbach** [comment]
Yep, works fine. Thanks!
