### ISSUE TITLE
Boolean command transform not saved if FALSE

### ISSUE THREAD

**Issue by minedaddy** [hufftheweevil/node-red-contrib-things#22]
In the SETUP properties node and in both the Thing-Type level and Thing level command tabs, selecting transform to a Boolean data type value of False is not saved in the node. The transform flag is simply cleared. Only the Boolean False setting is not saved. Selecting Boolean data type with a value of TRUE, the transform is saved as expected.

**Comment by hufftheweevil** [comment]
It's funny - I just found this bug myself yesterday and planned to work on it today. I've got the fix already and will release soon, with a few other minor features added (unrelated to this issue).

**Comment by hufftheweevil** [comment]
Fixed in [v3.1.0](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v3.1.0)
