### ISSUE TITLE
Question/Bug?: Trigger nodes not called for proxied states.

### ISSUE THREAD

**Issue by AmyAmy** [hufftheweevil/node-red-contrib-things#25]
Hi!

I love Things, makes getting my home automation flows soooo much more structured and more manageable.

Lately I've been trying out the more advanced features of Things, and I'm running into an issue:

It seems that trigger nodes listening for a proxied state variable, or for "All Updates" only actually trigger when a change is made to a non-proxied state variable.

For me atleast, this makes proxied state useless. Is there a way I can work around this?

The only thing I could think of was adding a dummy boolean to all objects with proxied state, find them with the `Thing List` and toggle it every second. But since I mostly have "All Updates" listeners, this causes triggers to be triggered waaaaaaaaaay to often, and just feels like an ugly hack.

Before using proxied state I used to have pages of triggers which copy their values to other Things, to which I'd often forget to add new Things, and just added boilerplate/clutter, so I do really like the idea of these proxies :)

**Comment by hufftheweevil** [comment]
If I'm understanding your use case correctly, it should be working as you expect it to.

"All Updates" should be used with caution and it should only be used when there is a specific reason for it.

But proxied state triggers should work just as expected. Are you able to export and share your flow so that I can take a close look?

**Comment by AmyAmy** [comment]
Hi,

I made some simplified test flows, initially to show you the problem I was having, but you are absolutely right, they work as I would expect. So I must have done something wrong myself, sorry!

The flows currently are a complete mess, so I won't dare to ask you to look at them, I'll investigate the issues further my self.

Thanks for your time!

**Comment by AmyAmy** [comment]
Hi again, I may have closed the issue a bit too early; I've managed to reproduce the issue.

Haning a proxy defined it the type instead of a thing seems to cause the issue:

[25-proxy-test.json.txt](https://github.com/hufftheweevil/node-red-contrib-things/files/6175745/25-proxy-test.json.txt)
(renamed to .txt in order to upload to github)

Use the buttons 1 and 2 to set the state in `ThingA`.
(use the Thing Directory to see the state change in `ThingA`).

`StateA` in `TypeB` has a proxy to `StateA` in `ThingA`.
`ThingB` is of type `TypeB`.
Therefor I'd expect to see `StateA` change in `ThingB` too when buttons 1 and 2 are used.

`ThingB` has an own state `StateB`.
Use buttons 3 and 4 to set `StateB`.
When updating `StateB` this also updates `StateA`, but this thus depends on making state changes to `ThingB`.

hope this helps to reproduce the issue!

**Comment by AmyAmy** [comment]
Oh, yeah, if it wasn't clear from the description: workaround for now can be to move the proxied state into all the things of type TypeB.

**Comment by hufftheweevil** [comment]
Thanks for the detailed example. I'm not able to look into it this weekend, but I will check it out as soon as I can and get back to you.

**Comment by hufftheweevil** [comment]
Fixed in [v3.1.2](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v3.1.2)

Thanks again for the detailed report. Helped me find the bug asap.
