### ISSUE TITLE
Some Things nodes not loaded in palette

### ISSUE THREAD

**Issue by minedaddy** [hufftheweevil/node-red-contrib-things#28]
Hello Mr. Weevil. I am a huge "things" fan but the most recent update only installs four of the nodes for me. 
![image](https://user-images.githubusercontent.com/30480168/113581725-87a20300-95f5-11eb-8265-8fdcd871a860.png)
I have NR v1.2.9 and have installed all Things releases as they became available so everything should be up-to-date, including the conversion from v2 to v3, although I also tried removing all "things" from my flows and made sure it was uninstalled. Installing Things from the palette manager and restarting Node Red gives the same result. The logs show now problems that I can see. Node Red thinks all is well but I do get 
![image](https://user-images.githubusercontent.com/30480168/113583405-9984a580-95f7-11eb-8640-e2f3019c70a0.png)
which is understandable.

I may have missed some detail somewhere and I'd appreciate any suggestions. I can do some tests for you if that helps.
Thanks!

**Comment by hufftheweevil** [comment]
That is very strange. Are you able to post the Node-RED console logs? I'm assuming there is an error getting logged when Node-RED starts that will help me figure out why it isn't loading those nodes.

**Comment by minedaddy** [comment]
I've removed Things completely from the palette, restarted Node Red and installed things 3.2.0 via the palette manager. The popup shows
![image](https://user-images.githubusercontent.com/30480168/113594184-56c9ca00-9605-11eb-97b8-e32ac67c7b5d.png)
but the palette shows
![image](https://user-images.githubusercontent.com/30480168/113594314-8678d200-9605-11eb-8387-a9be6488c9df.png)

while the console log shows:

5 Apr 11:49:21 - [info] Installing module: node-red-contrib-things, version: 3.2.0
5 Apr 11:49:30 - [info] Installed module: node-red-contrib-things
5 Apr 11:49:31 - [info] Added node types:
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing Setup : SyntaxError: Unexpected token '.'
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing Update : SyntaxError: Unexpected token '.' (line:3)
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing Trigger
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing Get
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing Test
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing List
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing Command : SyntaxError: Unexpected token '.'
5 Apr 11:49:31 - [info]  - node-red-contrib-things:Thing Process

This looks like the problem but I don't understand why it presents itself on my installation and not yours (or anyone else's).

**Comment by hufftheweevil** [comment]
Ah... I had thought I had already set this package up for Node >=14.0 only, but I see my badge on the readme still says >=12.0, so I shouldn't have used the ES2016 operator `?.` That is my fault - with so many packages I forget where I can use it and where I can't.

Two options for you right now: 1. Update your Node environment to >=14.0. That will eliminate the SyntaxError. Or 2. Wait until I can edit the code. I'm not able to do it right now, but maybe in a few hours.

Sorry about that!

**Comment by minedaddy** [comment]
I chose to update to Node 14.16 and every"thing" installs perfectly. No rush on the update (he said selfishly!). Thanks!

**Comment by hufftheweevil** [comment]
Glad to hear it. I'll probably just update the readme to show `>=14` anyway. It's time we all get on the bandwagon. Thanks for being a fan!
