### ISSUE TITLE
updates ??

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#29]
Hi there,

you have done a few updates but not mentioned what the improvements/changes are.  I understand that you are now relying on node.js 14, but what else has changed?

Would be great if you could update the changelog .. or give some update statements on the main page!

Still loving your THINGS and using it as a central component for all my sensors

**Comment by hufftheweevil** [comment]
Release [v3.2.0](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v3.2.0) contains all the most recent updates. And they are all listed on the changelog/release page.

v3.2.1 only added the node14 requirement (which was kind of just a bugfix)

**Comment by xX-Nexus-Xx** [comment]
thanks a lot ... i totally missed out your comments on the release page :(

Love your latest updates ... especially the feature to disable a THING
