### ISSUE TITLE
Issue with node-red docker image

### ISSUE THREAD

**Issue by gabric098** [hufftheweevil/node-red-contrib-things#30]
Hello,
I'm having issues installing the nodes on a node-red docker container running the official node-red image:
https://hub.docker.com/r/nodered/node-red/

This is the warnings I'm getting during installation:
```
-----------------------------------------------------------
2021-04-26T21:03:42.559Z Install : node-red-contrib-things 3.2.1

2021-04-26T21:03:43.537Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-things@3.2.1
2021-04-26T21:03:48.171Z [err] npm
2021-04-26T21:03:48.172Z [err]  
2021-04-26T21:03:48.172Z [err] WARN
2021-04-26T21:03:48.172Z [err]  
2021-04-26T21:03:48.172Z [err] notsup
2021-04-26T21:03:48.173Z [err]  Unsupported engine for node-red-contrib-things@3.2.1: wanted: {"node":">=14","npm":">=3"} (current: {"node":"12.22.1","npm":"6.14.12"})
2021-04-26T21:03:48.173Z [err] npm
2021-04-26T21:03:48.173Z [err]  
2021-04-26T21:03:48.174Z [err] WARN
2021-04-26T21:03:48.174Z [err]  
2021-04-26T21:03:48.174Z [err] notsup
2021-04-26T21:03:48.174Z [err]  Not compatible with your version of node/npm: node-red-contrib-things@3.2.1
2021-04-26T21:03:48.175Z [err] 
2021-04-26T21:03:48.178Z [out] + node-red-contrib-things@3.2.1
2021-04-26T21:03:48.178Z [out] added 2 packages from 2 contributors in 3.301s
2021-04-26T21:03:48.206Z rc=0
```

And once I reboot node-red container I get these messages:

```
26 Apr 21:05:45 - [warn] ------------------------------------------------------
26 Apr 21:05:45 - [warn] [node-red-contrib-things/setup] SyntaxError: Unexpected token '.' (line:223)
26 Apr 21:05:45 - [warn] [node-red-contrib-things/update] SyntaxError: Unexpected token '.' (line:3)
26 Apr 21:05:45 - [warn] [node-red-contrib-things/command] SyntaxError: Unexpected token '.' (line:39)
26 Apr 21:05:45 - [warn] ------------------------------------------------------
```

As result setup, update and command node don't show in the node-red menu and they cannot be used.

Docker image is using an old version of node (v12.22.1) which doesn't support certain syntax features.
I know that the recommended solution would be to upgrade node version, unfortunately many people like me use the official node-red image from docker-hub and we're locked to that node version.

**Comment by hufftheweevil** [comment]
It is a shame that the docker image does not include a v14 yet. After all, that has been the [current active release](https://nodejs.org/en/about/releases/) for 6 months now.

I'll probably make a branch of this that will work with <12. I'll try to get that done tonight.

**Comment by gabric098** [comment]
Yeah, it's unfortunate that the docker image of node-red is still stuck on that old version. 
I forked your project and created a PR:
https://github.com/hufftheweevil/node-red-contrib-things/pull/31

Up to you how you want to handle it, of course not to be merged into master. Maybe a `node12` branch, or even better a `node-red-docker` branch
In case you need someone to maintain it version, I'm happy to do that.

Cheers.

**Comment by hufftheweevil** [comment]
Sounds like a good idea. I've added a `node-red-docker` branch to this repo, but I don't see a way to change your PR so that it merges with that branch instead of the master. Maybe you need to submit a different PR specific to that branch?

**Comment by gabric098** [comment]
Thanks @hufftheweevil I saw the new PR and the `node-red-docker` branch.
One last thing. I was wondering how we could make in a way that people could decide to install this version directly from the node-red palette menu and get the ability to update without having to go through the manual install process.

So I thought we could (in the `node-red-docker` branch) change the package.json name to something like `node-red-contrib-things-docker` (or something more meaningful). In this way we could publish the package to npm and https://flows.nodered.org/  as a separate package and keep the same version numbers as the original `node-red-contrib-things`.

Let me think what are your thoughts about this idea. If you're happy with that I can create a PR.

**Comment by hufftheweevil** [comment]
I'm not crazy about that idea, but I don't see any other way to make it installable from the palette menu. It would be nice to see some more options from the palette menu, to allow other git branches and what not. But I digress.

So yeah we can do that. I have a feeling that the docker container will be upgraded to 14 soon (at least I have to imagine so), so this wouldn't need to go on for that long.

**Comment by gabric098** [comment]
Yeah, I'm totally with you, unfortunately node-red palette doesn't give you the possibility of choosing a specific version, you can only update to the latest version (according to semver).
See what looks to me, after installing manually the -node12 version
![Screen Shot 2021-04-29 at 22 11 36](https://user-images.githubusercontent.com/609622/116612618-0e69a780-a938-11eb-88b1-c9b2efaed616.png)

As side note: I was reading this article on node-red future:
https://nodered.org/blog/2020/07/01/release-plans

Apparently 2.x will be using node 14, even though the diagram is not super clear.

I'll work on the PR for changing the name on the `node-red-docker` branch. Probably you'll still need to manually publish it on npm and node-red (unless you have some form of automatic process to do that)

**Comment by gabric098** [comment]
PR created: https://github.com/hufftheweevil/node-red-contrib-things/pull/33

**Comment by hufftheweevil** [comment]
I'm cleaning up open issues. Is this still a valid issue now that we have Node-RED 2.x? If no comment is left in the next few days, I'll close this.
