### ISSUE TITLE
Lost states after nore red reboot

### ISSUE THREAD

**Issue by Fernando-Checa** [hufftheweevil/node-red-contrib-things#36]
I just noticed that my things states get lost (back to their defined value) after a nore red reboot.
Is there a way to persist this data?

**Comment by hufftheweevil** [comment]
Please see this closed issue: https://github.com/hufftheweevil/node-red-contrib-things/issues/15

**Comment by Fernando-Checa** [comment]
Thanks for the answer.
However, what type of storage should I use in your solution?
Default or my permanent one.
![imagen](https://user-images.githubusercontent.com/1741686/145679847-08480b38-391d-452b-989d-284ee6f95c7f.png)

**Comment by hufftheweevil** [comment]
Hmm, that looks like a new feature that I'm not familiar with. I would assume default.

**Comment by Fernando-Checa** [comment]
When you define a new persistent storage it appears there for you to choose from.
Default is the default one :-) which resides in memory and is lost after a reboot, and the one you define as persistent, resides on disk and survives reboots.

I'll make some tests.
Thanks for this amazing work!

**Comment by Fernando-Checa** [comment]
I tried both storages with no luck.
No matter what I inject in the storage, the state of my things is reset to default.
Any other ideas I could try?

**Comment by Fernando-Checa** [comment]
Well, it seems my default storage was on memory.
I modified the config file with this:

`contextStorage: {
        default: "disco",
        memoryOnly: { module: 'memory' },
        disco: { module: 'localfilesystem' }
     },`

so the default storage is the persistent one.
No w it seems it's working as expected.

Thanks again for the help.

**Comment by Fernando-Checa** [comment]
I think I talked too soon.. 
Now I'm getting this warnings.. 
I don't know if they a related to THINGS or not.. I'll keep you posted.

![imagen](https://user-images.githubusercontent.com/1741686/145717874-9594ca94-2acb-4193-a65c-20e72780c640.png)

**Comment by Fernando-Checa** [comment]
Well, it was a rogue node not related to things, so I guess everything works now as it's supposed to.

Thanks!

**Comment by hufftheweevil** [comment]
Glad to see you figured it out. Sorry I couldn't be more help - I haven't been doing too much with node-red at the moment.
