### ISSUE TITLE
Request for sample - Command & StatusFn

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#39]
Hi, 
I'm using your nodes (basic functionality) for a while and really happy about it .. works like a charm.

I have not yet used the features of "Command" & "StatusFn".. could you pls provide an example on how to use em properly? 

Additionally a sample for the "Children" functionality would be nice

thanks for this great node and all your support

**Comment by hufftheweevil** [comment]
Added a few more in [v3.2.4](https://github.com/hufftheweevil/node-red-contrib-things/releases/tag/v3.2.4)

The `transformCommands` example also includes a status function example.

The `forwardCommands` example also includes a children example
