### ISSUE TITLE
Clarification:  xxx waiting on (yy)

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#6]
I often see messages like below in THING-update node .. feed coming in from MQTT

> Motion waiting on (5) Motion.Bed, Motion.Doorbell, Motion.Dummy, Motion.Hallway, Motion.Toilett2

What does that mean , what is the implication of this message? 

regards

**Comment by hufftheweevil** [comment]
That means you specified a thing *type* in the properties for an **update** node and that particular node has not yet received any state updates for those things listed. I created it as a way to ensure all my devices of a particular *type* actually communicate into Node-RED.

If you don't want to see the status message, just remove the *type* from the configuration. It doesn't have any other consequences.

**Comment by xX-Nexus-Xx** [comment]
understood.. good idea ;)
