### ISSUE TITLE
Setup-Node stuck in "initializing" stage

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#7]
Hi,

I just updated to your latest node and was adding a new THING component ("Sensor") using setup. I setup just 1 new item and pushed deploy. 

- After the deploy, the SETUP node for "Sensor" is stuck in the **initializing** stage.
- ![image](https://user-images.githubusercontent.com/2195190/96671434-764d9d00-13ad-11eb-8406-2f85519d9035.png)

- I went into Setup node which was created earlier ("RF") and pressed the new "Config" button and the system became unresponsive
- I have done a reload but the 2 SETUP nodes ("Sensor" & "RF") remain in **initialize** stage
![image](https://user-images.githubusercontent.com/2195190/96671608-efe58b00-13ad-11eb-8459-d3c006590d03.png)
- I did a restart Node-red but the 2 THING items remain in initializing stage
- All other THING items are working fine
![image](https://user-images.githubusercontent.com/2195190/96672043-0b9d6100-13af-11eb-842e-f2253c05e28d.png)

Any idea?

**Comment by hufftheweevil** [comment]
Wow - either I don't understand `npm publish` or they have changed something recently. Either way, somehow it had included something I was working on for the next release, prematurely. I've removed that new work and re-published. Please be sure to get `v2.4.3`. It should be available via the library/palette momentarily.
 Sorry for the confusion!

**Comment by xX-Nexus-Xx** [comment]
thx a lot ... its back working again
