### ISSUE TITLE
Version 2.4.5 is crashing Node-Red

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#8]
your latest version (2.4.5) is crashing Node-Red ... no changes done to the flow

`23 Oct 15:53:52 - [info] Started flows

23 Oct 15:53:52 - [red] Uncaught Exception:

23 Oct 15:53:52 - TypeError: THINGS.filter(...).flatMap is not a function`

**Comment by hufftheweevil** [comment]
You need to upgrade node to version 12 or 14. Version 10 or below is not supported.

**Comment by xX-Nexus-Xx** [comment]
hmm... i'm using the official Node-Red docker (node 10) .. I'll have to figure out how to upgrade the image ;)

thanks

**Comment by hufftheweevil** [comment]
Looks like you need to specify the tag for v12: `docker pull nodered/node-red:latest-12`
