### ISSUE TITLE
Feature request:   set TOPIC in trigger & list nodes

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [hufftheweevil/node-red-contrib-things#9]
I'm currently re-writing most of my node logic to implement your THING topic.

Is it possible to modify your trigger & list node to set the payload topic in the same way as you did in your process node. The default msg.topic=THING.name is not always helpful and often needs to be changed afterwards!

thanks for considering

**Comment by hufftheweevil** [comment]
Quite ironic... I made this _exact_ change in the code probably 3 hours before you posted this. It will be released today or tomorrow along with several other improvements. Thanks for the suggestion!

**Comment by xX-Nexus-Xx** [comment]
im looking forward to it

**Comment by hufftheweevil** [comment]
Added in v3.0.0 which has been released as RC1 for now. It is not yet published on npm or Node-RED library. Install directly for now. Regular release will come early next week.
